In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
## Sentence
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabolary size.
voc_size=10000

In [24]:
## One hot representation
one_hot_repr=[one_hot(words, voc_size) for words in sent]

In [25]:
one_hot_repr

[[2152, 2119, 7454, 7005],
 [2152, 2119, 7454, 7756],
 [2152, 3151, 7454, 7856],
 [42, 2073, 2020, 1942, 3592],
 [42, 2073, 2020, 1942, 19],
 [7360, 2152, 7421, 7454, 3312],
 [2309, 1851, 2943, 1942]]

In [26]:
## WOrd Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
import numpy as np

In [28]:
sent_length=10
embedd_pad=pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)

In [29]:
embedd_pad

array([[   0,    0,    0,    0,    0,    0, 2152, 2119, 7454, 7005],
       [   0,    0,    0,    0,    0,    0, 2152, 2119, 7454, 7756],
       [   0,    0,    0,    0,    0,    0, 2152, 3151, 7454, 7856],
       [   0,    0,    0,    0,    0,   42, 2073, 2020, 1942, 3592],
       [   0,    0,    0,    0,    0,   42, 2073, 2020, 1942,   19],
       [   0,    0,    0,    0,    0, 7360, 2152, 7421, 7454, 3312],
       [   0,    0,    0,    0,    0,    0, 2309, 1851, 2943, 1942]],
      dtype=int32)

In [30]:
## Feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
embedd_pad[0]

array([   0,    0,    0,    0,    0,    0, 2152, 2119, 7454, 7005],
      dtype=int32)

In [33]:
model.predict(embedd_pad)

1/1 [==============================] - 0s 49ms/step


array([[[ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.03315644, -0.01487659,  0.00691245,  0.00042899,
          0.01580191, -0.0021052 ,  0.03706745, -0.04172432,
          0.02364243,  0.02440404],
        [ 0.01325095, -0.00091328,  0.04700035, -0.0